//
//  SparrowEmojiPlugin+Softbank.m
//  SparrowEmojiPlugin
//
//  Created by SKAhack on 11/03/12.
//  Copyright 2011 All rights reserved.
//

#import "SparrowEmojiPlugin+Softbank.h"


@implementation SparrowEmojiPlugin (Softbank)

- (NSString *)replaceSoftbankEmoji:(NSString *)message {
    NSMutableString *str = [NSMutableString stringWithString:message];
    
    NSString *f1 = @"<img src=\"http://mail.google.com/mail/e/softbank_ne_jp/";
    NSString *f2 = @"\" style=\"margin-top: 0px; margin-right: 0.2ex; margin-bottom: 0px; margin-left: 0.2ex; vertical-align: middle; \">";
    
    
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE001" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"19B", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE002" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"19C", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE003" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"823", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE004" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"19D", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE005" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"19E", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE006" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4CF", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE007" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4CC", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE008" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4EF", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE009" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"523", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE00A" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"525", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE00B" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"528", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE00C" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"538", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE00D" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B96", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE00E" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B97", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE00F" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B98", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE010" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B96", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE011" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B94", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE012" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B95", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE013" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"7D5", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE014" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"7D2", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE015" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"7D3", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE016" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"7D1", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE017" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"7DA", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE018" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"7D4", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE019" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1BD", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE01A" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1BE", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE01B" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"7E5", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE01C" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"7EA", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE01D" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"7E9", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE01E" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"7DF", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE01F" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"7E3", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE020" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B09", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE021" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B04", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE022" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B0C", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE023" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B0E", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE024" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"01E", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE025" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"01F", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE026" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"020", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE027" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"021", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE028" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"022", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE029" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"023", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE02A" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"024", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE02B" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"025", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE02C" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"026", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE02D" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"027", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE02E" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"028", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE02F" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"029", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE030" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"040", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE031" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4D2", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE032" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"041", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE033" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"512", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE034" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"825", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE035" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"826", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE036" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4B0", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE037" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4BB", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE038" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4B2", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE039" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"7EC", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE03A" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"7F5", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE03B" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4C3", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE03C" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"800", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE03D" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"801", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE03E" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"813", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE03F" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B82", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE040" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"815", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE041" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"816", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE042" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"818", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE043" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"980", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE044" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"982", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE045" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"981", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE046" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"962", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE047" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"983", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE048" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"003", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE049" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"001", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE04A" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"000", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE04B" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"002", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE04C" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"014", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE04D" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"009", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE04E" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1AF", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE04F" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1B8", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE050" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1C0", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE051" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1C1", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE052" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1B7", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE053" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1C2", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE054" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1C3", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE055" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1BC", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE056" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"335", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE057" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"330", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE058" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"323", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE059" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"320", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE05A" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4F4", f2]]];
    
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE101" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"52C", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE102" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"52E", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE103" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"52B", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE104" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"526", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE105" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"329", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE106" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"327", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE107" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"341", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE108" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"344", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE109" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1C4", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE10A" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1C5", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE10B" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1BF", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE10C" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1B0", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE10D" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"7ED", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE10E" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4D1", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE10F" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B56", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE110" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"03C", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE111" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"827", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE112" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"510", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE113" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B85", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE114" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4F5", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE115" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"7D9", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE116" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4CA", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE117" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"515", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE118" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"03F", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE119" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"042", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE11A" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1B2", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE11B" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1AE", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE11C" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1B3", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE11D" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4F6", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE11E" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"53B", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE11F" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"537", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE120" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"960", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE121" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4BC", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE122" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"7FB", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE123" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"7FA", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE124" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"7FD", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE125" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"807", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE126" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"81D", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE127" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"81E", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE128" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"81F", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE129" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"820", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE12A" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"81C", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE12B" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1B1", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE12C" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"81B", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE12D" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"80B", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE12E" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B32", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE12F" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4DD", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE130" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"80C", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE131" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"7DB", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE132" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"7D7", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE133" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"80D", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE134" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"7DC", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE135" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"7EE", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE136" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"7EB", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE137" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"7F8", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE138" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B33", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE139" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B34", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE13A" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B35", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE13B" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"509", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE13C" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B59", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE13D" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"004", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE13E" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4D6", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE13F" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"505", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE140" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"507", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE141" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"821", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE142" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"52F", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE143" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"514", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE144" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B86", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE145" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B87", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE146" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"00B", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE147" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"965", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE148" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"546", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE149" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4DE", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE14A" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4DF", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE14B" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"531", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE14C" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B5E", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE14D" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4B5", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE14E" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"7F7", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE14F" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"7F6", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE150" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"7E7", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE151" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"506", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE152" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1A1", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE153" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4B3", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE154" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4B6", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE155" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4B4", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE156" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4B9", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE157" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4BA", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE158" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4B7", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE159" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"7E6", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE15A" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"7EF", f2]]];
    
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE201" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"7F0", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE202" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"7E8", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE203" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B24", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE204" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B19", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE205" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B62", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE206" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B61", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE207" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B25", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE208" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B1F", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE209" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"044", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE20A" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B20", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE20B" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"838", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE20C" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B1A", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE20D" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B1C", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE20E" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B1B", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE20F" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B1D", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE210" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"82C", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE211" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"82B", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE212" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B36", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE213" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B37", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE214" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B38", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE215" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B39", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE216" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B3A", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE217" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B3B", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE218" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B3C", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE219" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B63", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE21A" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B64", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE21B" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B67", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE21C" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"82E", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE21D" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"82F", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE21E" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"830", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE21F" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"831", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE220" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"832", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE221" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"833", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE222" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"834", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE223" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"835", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE224" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"836", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE225" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"837", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE226" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B3D", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE227" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B3E", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE228" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B3F", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE229" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B81", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE22A" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B31", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE22B" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B2F", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE22C" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B40", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE22D" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B41", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE22E" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B99", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE22F" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B9A", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE230" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B9B", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE231" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B9C", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE232" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"AF8", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE233" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"AF9", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE234" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"AFA", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE235" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"AFB", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE236" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"AF0", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE237" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"AF2", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE238" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"AF1", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE239" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"AF3", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE23A" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"AFC", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE23B" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"AFD", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE23C" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"AFE", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE23D" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"AFF", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE23E" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4F8", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE23F" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"02B", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE240" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"02C", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE241" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"02D", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE242" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"02E", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE243" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"02F", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE244" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"030", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE245" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"031", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE246" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"032", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE247" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"033", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE248" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"034", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE249" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"035", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE24A" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"036", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE24B" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"037", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE24C" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B42", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE24D" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B27", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE24E" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B29", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE24F" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B2D", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE250" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"839", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE251" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"83A", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE252" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B23", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE253" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1B4", f2]]];
    
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE301" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"527", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE302" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4D3", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE303" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"045", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE304" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"03D", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE305" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"046", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE306" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"828", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE307" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"047", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE308" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"048", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE309" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"508", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE30A" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"803", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE30B" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"985", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE30C" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"987", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE30D" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B43", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE30E" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B1E", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE30F" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"50A", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE310" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"516", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE311" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"517", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE312" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B58", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE313" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"53E", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE314" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"50F", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE315" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B2B", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE316" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"53C", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE317" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"52F", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE318" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4D4", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE319" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4D5", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE31A" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4D7", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE31B" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4D8", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE31C" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"195", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE31D" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"196", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE31E" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"197", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE31F" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"198", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE320" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"199", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE321" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4D9", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE322" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4DA", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE323" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4F0", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE324" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"808", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE325" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4F2", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE326" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"814", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE327" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B0D", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE328" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B11", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE329" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B12", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE32A" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B13", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE32B" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B14", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE32C" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B15", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE32D" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B16", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE32E" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B60", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE32F" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B68", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE330" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B5D", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE331" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B5B", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE332" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B44", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE333" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B45", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE334" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B57", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE335" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B69", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE336" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B0A", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE337" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B0B", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE338" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"984", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE339" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"964", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE33A" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"966", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE33B" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"967", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE33C" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"968", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE33D" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"969", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE33E" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"96A", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE33F" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"96B", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE340" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"963", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE341" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"96C", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE342" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"961", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE343" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"96D", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE344" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"96E", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE345" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"051", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE346" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"052", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE347" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"053", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE348" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"054", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE349" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"055", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE34A" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"056", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE34B" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"511", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE34C" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"96F", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE34D" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"970", f2]]];
    
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE401" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"345", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE402" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"343", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE403" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"340", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE404" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"328", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE405" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"347", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE406" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"33C", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE407" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"33F", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE408" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"342", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE409" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"32A", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE40A" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"33E", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE40B" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"33B", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE40C" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"32E", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE40D" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"32F", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE40E" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"326", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE40F" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"325", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE410" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"322", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE411" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"33A", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE412" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"334", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE413" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"339", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE414" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"337", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE415" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"338", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE416" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"33D", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE417" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"32D", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE418" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"32C", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE419" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"190", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE41A" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"192", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE41B" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"191", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE41C" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"193", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE41D" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"35B", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE41E" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B9D", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE41F" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B9E", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE420" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B9F", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE421" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"BA0", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE422" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"BA1", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE423" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"351", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE424" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"352", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE425" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"829", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE426" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"353", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE427" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"358", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE428" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1A0", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE429" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1A2", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE42A" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"7D6", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE42B" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"7DD", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE42C" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"80E", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE42D" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"7DE", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE42E" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"7E5", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE42F" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"7F1", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE430" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"7F2", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE431" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"7F3", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE432" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"7F4", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE433" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"7FE", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE434" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"7E0", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE435" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"7E2", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE436" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"518", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE437" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B17", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE438" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"519", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE439" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"51A", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE43A" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"51B", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE43B" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"51C", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE43C" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"007", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE43D" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"82A", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE43E" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"038", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE43F" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"971", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE440" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"51D", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE441" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1C6", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE442" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"51E", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE443" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"005", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE444" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"049", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE445" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"51F", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE446" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"017", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE447" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"043", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE448" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"513", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE449" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"00A", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE44A" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"00C", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE44B" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"008", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE44C" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"00D", f2]]];
    
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE501" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4B8", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE502" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"804", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE503" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"805", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE504" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4BD", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE505" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4BE", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE506" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4BF", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE507" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"802", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE508" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4C0", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE509" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4C4", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE50A" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4C5", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE50B" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4E5", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE50C" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4E6", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE50D" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4E7", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE50E" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4E8", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE50F" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4E9", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE510" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4EA", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE511" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4EB", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE512" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4EC", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE513" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4ED", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE514" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4EE", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE515" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1A4", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE516" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1A5", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE517" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1A6", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE518" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1A7", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE519" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1A8", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE51A" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1A9", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE51B" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1AA", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE51C" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1AB", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE51D" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4C6", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE51E" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1B5", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE51F" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1B6", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE520" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1C7", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE521" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1C8", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE522" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1C9", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE523" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1BA", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE524" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1CA", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE525" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1CB", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE526" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1CC", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE527" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1CD", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE528" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1CE", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE529" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1CF", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE52A" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1D0", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE52B" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1D1", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE52C" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1D2", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE52D" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1D3", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE52E" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1D4", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE52F" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1D5", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE530" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1D6", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE531" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1D7", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE532" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"50B", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE533" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"50C", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE534" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"50D", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE535" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"50E", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE536" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"553", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE537" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B2A", f2]]];

    return str;
}

- (size_t)convertSoftBankSJISToUTF8:(iconv_t)con inbuf:(char **)inbuf inbytesleft:(size_t *)inbytesleft outbuf:(char **)outbuf outbytesleft:(size_t *)outbytesleft {
    
    char *_inbuf = *inbuf, *_outbuf = *outbuf;
    unsigned char c1 = _inbuf[0];
    unsigned char c2 = _inbuf[1];
    
    unsigned short codepoint = 0;
    
    if (c1 == 0xF7) {
        if (c2 >= 0x41 && c2 <= 0x9B) {
            codepoint = 0xE100 + (c2 - 0x40 - (c2 >= 0x80 ? 0x01 : 0x00));
        } else if (c2 >= 0xA1 && c2 <= 0xF3) {
            codepoint = 0xE200 + (c2 - 0xA0);
        }
    } else if (c1 == 0xF9) {
        if (c2 >= 0x41 && c2 <= 0x9B) {
            codepoint = 0xE000 + (c2 - 0x40 - (c2 >= 0x80 ? 0x01 : 0x00));
        } else if (c2 >= 0xA1 && c2 <= 0xED) {
            codepoint = 0xE300 + (c2 - 0xA0);
        }
    } else if (c1 == 0xFB) {
        if (c2 >= 0x41 && c2 <= 0x8D) {
            codepoint = 0xE400 + (c2 - 0x40 - (c2 >= 0x80 ? 0x01 : 0x00));
        } else if (c2 >= 0xA1 && c2 <= 0xD7) {
            codepoint = 0xE500 + (c2 - 0xA0);
        }
    }
    
    if (codepoint != 0) {
        _inbuf += 2;
        _outbuf[0] = codepoint>>12 & 0x0F | 0xE0;
        _outbuf[1] = codepoint>>6  & 0x3F | 0x80;
        _outbuf[2] = codepoint     & 0x3F | 0x80;
        _outbuf += 3;
        
        
        *inbuf = _inbuf;
        *outbuf = _outbuf;
        *inbytesleft -= 2;
        *outbytesleft += 3;
        
        return 2;
    } else {
        return (size_t) - 1;
    }
}

@end
