//
//  SparrowEmojiPlugin+Au.m
//  SparrowEmojiPlugin
//
//  Created by SKAhack on 11/03/18.
//  Copyright 2011 __MyCompanyName__. All rights reserved.
//

#import "SparrowEmojiPlugin+Kddi.h"


@implementation SparrowEmojiPlugin (Kddi)

- (NSString *)replaceKddiEmoji:(NSString *)message {
    NSMutableString *str = [NSMutableString stringWithString:message];
    
    NSString *f1 = @"<img src=\"http://mail.google.com/mail/e/ezweb_ne_jp/";
    NSString *f2 = @"\" style=\"margin-top: 0px; margin-right: 0.2ex; margin-bottom: 0px; margin-left: 0.2ex; vertical-align: middle; \">";
    
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE468" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B6A", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE469" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"005", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE46A" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"7F7", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE46B" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"7D9", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE46C" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B61", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE46D" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"7FD", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE46E" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"80D", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE46F" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"520", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE470" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1C3", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE471" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"330", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE472" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"320", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE473" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"33A", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE474" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"346", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE475" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B59", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE476" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B56", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE477" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B0E", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE478" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B0F", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE479" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B61", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE47A" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B58", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE47B" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4F6", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE47C" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"01B", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE47D" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B1E", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE47E" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B1F", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE47F" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B20", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE480" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"044", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE481" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B23", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE482" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B04", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE483" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B09", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE484" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B26", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE485" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"003", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE486" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"014", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE487" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"004", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE488" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"000", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE489" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"016", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE48A" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"00E", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE48B" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B68", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE48C" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"002", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE48D" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"001", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE48E" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"00F", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE48F" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"02B", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE490" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"02C", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE491" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"02D", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE492" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"02E", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE493" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"02F", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE494" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"030", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE495" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"031", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE496" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"032", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE497" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"033", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE498" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"034", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE499" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"035", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE49A" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"036", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE49B" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"037", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE49C" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4F0", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE49D" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"547", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE49E" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"807", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE49F" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"546", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE4A0" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"53A", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE4A1" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"539", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE4A2" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"551", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE4A3" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4B6", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE4A4" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4B9", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE4A5" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"506", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE4A6" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"7F6", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE4A7" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"7E7", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE4A8" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"531", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE4A9" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4C1", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE4AA" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4B5", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE4AB" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4B0", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE4AC" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"980", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE4AD" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4B2", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE4AE" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"7EB", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE4AF" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"7E6", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE4B0" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"7E3", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE4B1" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"7E4", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE4B2" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"7F1", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE4B3" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"7E9", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE4B4" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"7EA", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE4B5" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"7DF", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE4B6" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"7D4", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE4B7" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"7D3", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE4B8" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"7D8", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE4B9" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"7D7", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE48A" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"7D1", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE4BB" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"7DD", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE4BC" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"7FA", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE4BD" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4C2", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE4BE" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"808", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE4BF" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"010", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE4C0" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4C4", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE4C1" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"986", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE4C2" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"982", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE4C3" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"983", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE4C4" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"972", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE4C5" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"80C", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE4C6" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"80A", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE4C7" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4DD", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE4C8" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"80F", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE4C9" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"512", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE4CA" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"040", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE4CB" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1AE", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE4CC" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4E5", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE4CD" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"054", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE4CE" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"03F", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE4CF" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"510", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE4D0" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"962", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE4D1" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"965", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE4D2" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"04F", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE4D3" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1D9", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE4D4" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"053", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE4D5" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"961", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE4D6" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"960", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE4D7" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1D2", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE4D8" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1BE", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE4D9" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1C4", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE4DA" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1D7", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE4DB" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1B8", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE4DC" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1BC", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE4DD" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1DA", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE4DE" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1BF", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE4DF" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1D8", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE4E0" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1BA", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE4E1" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1B7", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE4E2" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"047", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE4E3" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"046", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE4E4" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"03D", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE4E5" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B57", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE4E6" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B5C", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE4E7" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"329", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE4E8" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B4F", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE4E9" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B5E", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE4EA" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B12", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE4EB" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"823", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE4EC" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1B1", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE4ED" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"973", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE4EE" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1DB", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE4EF" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1B2", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE4F0" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B7A", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE4F1" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B2B", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE4F2" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B7B", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE4F3" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B96", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE4F4" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B5D", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE4F5" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4F4", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE4F6" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B98", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE4F7" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B3D", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE4F8" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1B3", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE4F9" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B97", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE4FA" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"19C", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE4FB" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"333", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE4FC" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"19B", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE4FD" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"532", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE4FE" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4CE", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE4FF" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B9B", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE500" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B9C", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE501" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"19F", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE502" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"81C", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE503" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"800", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE504" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4DC", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE505" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"814", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE506" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"816", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE507" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"819", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE508" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"803", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE509" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"195", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE50A" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4F5", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE50B" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"505", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE50C" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"81D", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE50D" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4DB", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE50E" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1B0", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE50F" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B37", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE510" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"509", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE511" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"530", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE512" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4F2", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE513" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"03C", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE514" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"825", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE515" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4EF", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE516" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"53E", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE517" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"801", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE518" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B85", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE519" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B82", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE51A" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4D6", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE51B" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"52C", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE51C" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B86", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE51D" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"504", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE51E" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"524", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE51F" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"535", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE520" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"528", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE521" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"529", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE522" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"82E", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE523" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"82F", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE524" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"830", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE525" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"831", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE526" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"832", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE527" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"833", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE528" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"834", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE529" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"835", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE52A" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"836", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE52B" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"83B", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE52C" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"82D", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE52D" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"AFD", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE52E" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"AFC", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE52F" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"AFF", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE530" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"AFE", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE531" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B6B", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE532" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B6C", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE533" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B47", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE534" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B6D", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE535" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B6E", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE536" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B73", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE537" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B74", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE538" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B6B", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE539" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B6C", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE53A" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B65", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE53B" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B66", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE53C" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B51", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE53D" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B52", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE53E" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B62", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE53F" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"AF8", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE540" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"AF9", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE541" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B48", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE542" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B00", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE543" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B01", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE544" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B02", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE545" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B03", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE546" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B73", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE547" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B74", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE548" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B6D", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE549" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B6E", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE54A" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B63", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE54B" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B64", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE54C" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"AF2", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE54D" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"AF1", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE54E" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B2A", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE54F" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B53", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE550" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B45", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE551" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B46", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE552" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"AFA", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE553" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"AFB", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE554" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B54", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE555" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"AF0", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE556" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"AF3", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE557" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B49", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE558" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B29", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE559" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B2D", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE55A" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B78", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE55B" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B79", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE55C" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B88", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE55D" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B83", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE55E" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B4A", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE55F" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4FD", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE560" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"53F", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE561" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"540", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE562" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"53D", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE563" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"542", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE564" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"548", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE565" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4FF", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE566" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"500", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE567" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"501", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE568" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"502", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE569" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"541", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE56A" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"549", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE56B" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"545", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE56C" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"54D", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE56D" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"54E", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE56E" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"54F", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE56F" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"503", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE570" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"550", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE571" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"7F5", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE572" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4C7", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE573" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4E6", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE574" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"54A", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE575" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"54B", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE576" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"54C", f2]]];
    //[str setString:[str stringByReplacingOccurrencesOfString:@"\uE577" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE578" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B21", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE579" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4E0", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE57A" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"01D", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE57B" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"01C", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE57C" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4E1", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE57D" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4E2", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE57E" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4F9", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE57F" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4FA", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE580" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"820", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE581" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4CB", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE582" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"53C", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE583" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4FB", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE584" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4FC", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE585" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4E3", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE586" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"83C", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE587" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4C9", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE588" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"525", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE589" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4FE", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE58A" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B4B", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE58B" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"822", f2]]];
    //[str setString:[str stringByReplacingOccurrencesOfString:@"\uE58C" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"", f2]]];
    //[str setString:[str stringByReplacingOccurrencesOfString:@"\uE58D" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"", f2]]];
    //[str setString:[str stringByReplacingOccurrencesOfString:@"\uE58E" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE58F" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"543", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE590" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"544", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE591" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"52A", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE592" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"533", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE593" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"534", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE594" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"02A", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE595" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B0C", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE596" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"523", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE597" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"981", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE598" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"006", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE599" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"7D2", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE59A" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"7D6", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE59B" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"522", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE59C" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"804", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE59D" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"809", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE59E" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"806", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE59F" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"50F", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE5A0" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"511", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE5A1" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B1B", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE5A2" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B1C", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE5A3" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B1D", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE5A4" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"190", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE5A5" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"191", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE5A6" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B94", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE5A7" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B95", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE5A8" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"011", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE5A9" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"012", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE5AA" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"013", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE5AB" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B84", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE5AC" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"837", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE5AD" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B27", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE5AE" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"324", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE5AF" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B18", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE5B0" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B5A", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE5B1" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B5B", f2]]];
    //[str setString:[str stringByReplacingOccurrencesOfString:@"\uE5B2" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE5B3" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"039", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE5B4" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"963", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEAFB" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"96F", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEAFC" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"970", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEAFD" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"326", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEAFE" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"321", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEAFF" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"328", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB00" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"33C", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB01" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"33F", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB02" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"342", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB03" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"33E", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB04" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"33B", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB05" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"32E", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB06" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"32F", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB07" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"326", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB08" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"322", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB09" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"325", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB0A" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"81A", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB0B" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"335", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB0C" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"32D", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB0D" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"32C", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE5B5" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B36", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE5B6" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4CF", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE5B7" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4CC", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE5B8" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"538", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE5B9" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"81F", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE5BA" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"041", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE5BB" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4BB", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE5BC" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"7E0", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE5BD" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4C3", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE5BE" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"813", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE5BF" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1AF", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE5C0" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1C0", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE5C1" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1C1", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE5C2" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1C2", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE5C3" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"347", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE5C4" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"327", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE5C5" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"341", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE5C6" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"344", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE5C7" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1C5", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE5C8" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"7ED", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE5C9" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4D1", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE5CA" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"827", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE5CB" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4CA", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE5CC" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"515", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE5CD" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"042", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE5CE" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"53B", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE5CF" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4BC", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE5D0" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"7FB", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE5D1" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"80B", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE5D2" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B32", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE5D3" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"7DB", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE5D4" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1DC", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE5D5" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4EB", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE5D6" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4EC", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE5D7" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"7F8", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE5D8" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"505", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE5D9" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"514", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE5DA" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"00B", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE5DB" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1DD", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE5DC" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4DF", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE5DD" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1A1", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE5DE" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4B3", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uE5DF" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4B4", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEA80" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4BA", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEA81" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4B7", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEA82" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"7E8", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEA83" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B25", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEA84" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"838", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEA85" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B38", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEA86" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B3E", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEA87" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B3F", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEA88" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B81", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEA89" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B31", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEA8A" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B2F", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEA8B" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B40", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEA8C" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B41", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEA8D" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B99", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEA8E" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B9A", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEA8F" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4F7", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEA90" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"839", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEA91" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"83A", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEA92" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"527", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEA93" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4D3", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEA94" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"045", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEA95" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"828", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEA96" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"048", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEA97" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"985", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEA98" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"987", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEA99" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B43", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEA9A" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"50A", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEA9B" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4E7", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEA9C" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B89", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEA9D" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B8A", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEA9E" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B7C", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEA9F" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B7D", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEAA0" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B7E", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEAA1" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B7F", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEAA2" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B50", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEAA3" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B8B", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEAA4" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"536", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEAA5" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B8C", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEAA6" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B8D", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEAA7" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B8E", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEAA8" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B8F", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEAA9" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"526", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEAAA" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4B1", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEAAB" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"52D", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEAAC" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"552", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEAAD" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B90", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEAAE" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B91", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEAAF" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4E8", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEAB0" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4E9", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEAB1" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4EA", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEAB2" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4E9", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEAB3" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4EA", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEAB4" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4ED", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEAB5" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4EE", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEAB6" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1A4", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEAB7" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1A5", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEAB8" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1A6", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEAB9" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1A7", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEABA" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"516", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEABB" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"517", f2]]];
    //[str setString:[str stringByReplacingOccurrencesOfString:@"\uEABC" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEABD" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4D4", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEABE" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4D8", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEABF" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"196", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEAC0" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"198", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEAC1" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"199", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEAC2" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4D9", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEAC3" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4DA", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEAC4" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B1A", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEAC5" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B10", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEAC6" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B13", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEAC7" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B14", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEAC8" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B15", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEAC9" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B16", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEACA" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B60", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEACB" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"7D5", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEACC" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B44", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEACD" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"984", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEACE" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"964", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEACF" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"966", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEAD0" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"967", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEAD1" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"968", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEAD2" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"969", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEAD3" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"96A", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEAD4" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"969", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEAD5" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"96C", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEAD6" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"96D", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEAD7" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"96E", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEAD8" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"051", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEAD9" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1A8", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEADA" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1A9", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEADB" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1AA", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEADC" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1AB", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEADD" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1C7", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEADE" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1B6", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEADF" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1C9", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEAE0" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1CB", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEAE1" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1CC", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEAE2" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1CD", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEAE3" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1D1", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEAE4" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1D3", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEAE5" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1D4", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEAE6" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1D5", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEAE7" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1D6", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEAE8" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"50B", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEAE9" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"50C", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEAEA" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"50E", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEAEB" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"50D", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEAEC" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"553", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEAED" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4CD", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEAEE" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B22", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEAEF" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"AF4", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEAF0" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"AF5", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEAF1" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B05", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEAF2" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B06", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEAF3" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B08", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEAF4" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"057", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEAF5" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"058", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEAF6" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"059", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEAF7" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"050", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEAF8" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"052", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEAF9" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"055", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEAFA" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"056", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB0E" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"192", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB0F" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"193", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB10" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"35B", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB11" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B9E", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB12" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B9F", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB13" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"BA0", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB14" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B9D", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB15" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"351", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB16" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"352", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB17" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"04A", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB18" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"04B", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB19" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"04C", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB1A" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"05A", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB1B" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"974", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB1C" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"975", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB1D" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"976", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB1E" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"521", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB1F" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"988", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB20" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1DE", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB21" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"817", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB22" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"7DA", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB23" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"7FF", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB24" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"810", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB25" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1AC", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB26" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1AD", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB27" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1DF", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB28" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"194", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB29" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1E0", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB2A" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"04D", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB2B" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"977", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB2C" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"978", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB2D" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"979", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB2E" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"97A", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB2F" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"97B", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB30" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"97C", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB31" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"354", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB32" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"355", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB33" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"356", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB34" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"03A", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB35" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B17", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB36" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"353", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB37" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"829", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB38" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1A2", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB39" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"818", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB3A" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"80E", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB3B" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"7DE", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB3C" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"7F2", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB3D" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"7F3", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB3E" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"7F4", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB3F" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"7FE", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB40" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"518", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB41" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"519", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB42" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"51A", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB43" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"51B", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB44" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"51C", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB45" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"007", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB46" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1A3", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB47" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"971", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB48" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"51D", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB49" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1C6", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB4A" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"51E", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB4B" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"51F", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB4C" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"017", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB4D" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"00D", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB4E" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4B8", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB4F" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"00A", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB50" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"805", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB51" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4BD", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB52" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4BE", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB53" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4BF", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB54" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4C0", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB55" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B80", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB56" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"97D", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB57" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1E1", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB58" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1E2", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB59" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"97E", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB5A" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"05B", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB5B" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4E4", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB5C" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B5F", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB5D" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"33D", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB5E" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"34E", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB5F" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"03B", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB60" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"34B", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB61" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"348", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB62" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"52B", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB63" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"34A", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB64" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"334", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB65" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"34C", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB66" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"350", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB67" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"321", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB68" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"34D", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB69" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"339", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB6A" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"34F", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB6B" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4D5", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB6C" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4C8", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB6D" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"7EC", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB6E" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"811", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB6F" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"812", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB70" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"97F", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB71" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B92", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB72" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"7F0", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB73" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"7F9", f2]]];
    //[str setString:[str stringByReplacingOccurrencesOfString:@"\uEB74" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB75" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B0D", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB76" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1BB", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB77" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"4D0", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB78" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"824", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB79" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B91", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB7A" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"AF6", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB7B" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"AF7", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB7C" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"038", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB7D" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"03E", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB7E" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"1B9", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB7F" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"349", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB80" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"333", f2]]];
    //[str setString:[str stringByReplacingOccurrencesOfString:@"\uEB81" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB82" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"04E", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB83" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"B93", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB84" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"82C", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB85" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"357", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB86" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"358", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB87" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"359", f2]]];
    [str setString:[str stringByReplacingOccurrencesOfString:@"\uEB88" withString:[NSString stringWithFormat:@"%@%@%@", f1, @"35A", f2]]];

    
    return str;
}

- (int) convertISO2022JPToUTF8:(iconv_t)con inbuf:(char **)inbuf inbytesleft:(size_t *)inbytesleft outbuf:(char **)outbuf outbytesleft:(size_t *)outbytesleft {
    
    char *_inbuf = *inbuf, *_outbuf = *outbuf;
    char c1 = _inbuf[0];
    char c2 = _inbuf[1];
    
    unsigned short codepoint = (c1<<8) + c2;
    
    if (c1 >= 0x75 && c1 <= 0x7C) {
        if (c1 == 0x75 && (c2 >= 0x21 && c2 <= 0x7E)) {
            codepoint += 0x6F47;
        } else if (c1 == 0x76 && (c2 >= 0x21 && c2 <= 0x7E)) {
            codepoint += 0x6EA5;
        } else if (c1 == 0x77 && (c2 >= 0x21 && c2 <= 0x7E)) {
            codepoint += 0x6E03;
        } else if (c1 == 0x78) {
            if (c2 >= 0x21 && c2 <= 0x53) {
                codepoint += 0x6D61;
            } else if (c2 >= 0x54 && c2 <= 0x7E) {
                codepoint += 0x6D4E;
            }
        } else if (c1 == 0x79) {
            if (c2 >= 0x21 && c2 <= 0x33) {
                codepoint += 0x6CAC;
            } else if (c2 >= 0x34 && c2 <= 0x7E) {
                codepoint += 0x714C;
            }
        } else if (c1 == 0x7A) {
            if (c2 >= 0x21 && c2 <= 0x50) {
                codepoint += 0x70AA;
            } else if (c2 >= 0x51 && c2 <= 0x7E) {
                codepoint += 0x70BD;
            }
        } else if (c1 == 0x7B && (c2 >= 0x21 && c2 <= 0x6D)) {
            codepoint += 0x701B;
        }
    }
    
    if (codepoint != (c1<<8) + c2) {
        _inbuf += 2;
        _outbuf[0] = codepoint>>12 & 0x0F | 0xE0;
        _outbuf[1] = codepoint>>6  & 0x3F | 0x80;
        _outbuf[2] = codepoint     & 0x3F | 0x80;
        _outbuf += 3;
        
        
        *inbuf = _inbuf;
        *outbuf = _outbuf;
        *inbytesleft += 2;
        *outbytesleft += 3;
        
        return 2;
    } else {
        return 0;
    }
}

@end
